AWSTemplateFormatVersion: '2010-09-09'
Description: RDS MySQL DB Instance Stack with Public Access Enabled

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: travelog-vpc (VPC ID)
  PrivateSubnetAId:
    Type: AWS::EC2::Subnet::Id
    Description: travelog-private-db-a (AZ-A DB Subnet ID)
  PrivateSubnetCId:
    Type: AWS::EC2::Subnet::Id
    Description: travelog-private-db-c (AZ-C DB Subnet ID)
  ECSSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: RDS에 접근을 허용할 ECS Security Group ID (Source for Ingress)
  DbMasterUsername:
    Type: String
    Default: admin
    Description: RDS의 마스터 사용자 이름
  DbMasterPassword:
    Type: String
    Description: RDS의 마스터 사용자 비밀번호 (운영 환경에서는 Secrets Manager 사용 권장)
    NoEcho: true


Resources:

  #####################################################################
  # 1. RDS DB 서브넷 그룹
  #    - RDS 인스턴스를 배포할 Private Subnet 지정 (Multi-AZ)
  #####################################################################
  RDSDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub "${AWS::StackName}-db-subnet-group"
      DBSubnetGroupDescription: "DB Subnet Group for travelog RDS instance"
      SubnetIds:
        - !Ref PrivateSubnetAId
        - !Ref PrivateSubnetCId

  #####################################################################
  # 2. RDS 보안 그룹 (SG-RDS)
  #    - 인바운드 3306 포트를 ECS 보안 그룹에서만 허용
  #    - 아웃바운드는 템플릿에서 정의할 필요 없이 기본적으로 ALL-ALL 허용됨
  #####################################################################
  RDSDBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "SG-RDS-travelog"
      GroupDescription: "Security Group for RDS, allowing traffic only from ECS Security Group"
      VpcId: !Ref VpcId
      # 인바운드 규칙: ECS Security Group에서 3306 포트 접근 허용
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref ECSSecurityGroupId
      Tags:
        - Key: Name
          Value: "SG-RDS-travelog"

  #####################################################################
  # 3. RDS DB 인스턴스
  #####################################################################
  RDSDBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    Properties:
      # 인스턴스 및 엔진 설정
      DBName: "travelog"
      Engine: mysql
      EngineVersion: "8.0.43"
      Port: 3306
      DBInstanceClass: db.t3.micro
      MasterUsername: !Ref DbMasterUsername
      MasterUserPassword: !Ref DbMasterPassword

      # 네트워크 및 고가용성 설정
      DBSubnetGroupName: !Ref RDSDBSubnetGroup
      VPCSecurityGroups:
        - !GetAtt RDSDBSecurityGroup.GroupId
      MultiAZ: true

      # **요구사항 반영: Publicly Accessible 허용**
      PubliclyAccessible: true

      # 스토리지 설정
      AllocatedStorage: "20"
      StorageType: gp3

      # 백업 설정
      BackupRetentionPeriod: "7"

      # Tag for easy identification
      Tags:
        - Key: Project
          Value: "travelogs3-project2"
        - Key: Name
          Value: "travelog-mysql-db"

Outputs:
  DBEndpointAddress:
    Description: RDS DB Instance Endpoint Address
    Value: !GetAtt RDSDBInstance.Endpoint.Address
    Export:
      Name: "travelog-DBEndpoint"

  DBSecurityGroupId:
    Description: RDS Security Group ID
    Value: !Ref RDSDBSecurityGroup
    Export:
      Name: "travelog-DBSecurityGroupId"