AWSTemplateFormatVersion: '2010-09-09'
Description: RDS MySQL DB

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: travelog-vpc
  PrivateSubnetAId:
    Type: AWS::EC2::Subnet::Id
    Description: travelog-private-db-a
  PrivateSubnetCId:
    Type: AWS::EC2::Subnet::Id
    Description: travelog-private-db-c
  ECSSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: SG-RDS
  DbMasterUsername:
    Type: String
    Default: admin
    Description: RDS의 마스터 사용자 이름
  DbMasterPassword:
    Type: String
    Description: RDS의 마스터 사용자 비밀번호 (운영 환경에서는 Secrets Manager 사용 권장)
    NoEcho: true


Resources:

  #####################################################################
  # 1. RDS DB 서브넷 그룹
  #    - RDS 인스턴스를 배포할 Private Subnet 지정 (Multi-AZ)
  #####################################################################
  RDSDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      # AWS::StackName을 사용하여 스택 이름 기반의 고유한 이름을 생성합니다. (수정됨)
      DBSubnetGroupName: !Sub "${AWS::StackName}-db-subnet-group"
      DBSubnetGroupDescription: "DB Subnet Group for travelog RDS instance"
      SubnetIds:
        - !Ref PrivateSubnetAId
        - !Ref PrivateSubnetCId

  #####################################################################
  # 2. RDS 보안 그룹 (SG-RDS)
  #    - 인바운드 3306 포트를 ECS 보안 그룹에서만 허용
  #####################################################################
  RDSDBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "SG-RDS-travelog"
      GroupDescription: "Security Group for RDS, allowing traffic only from ECS Security Group"
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref ECSSecurityGroupId # SG-ECS에서만 3306 접근 허용
      Tags:
        - Key: Name
          Value: "SG-RDS-travelog"

  #####################################################################
  # 3. RDS DB 인스턴스
  #    - 요구 사항에 따른 구성 (MySQL 8.0.35, Multi-AZ, db.t3.micro)
  #####################################################################
  RDSDBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot # 스택 삭제 시 데이터 손실 방지를 위해 스냅샷 생성
    Properties:
      # 인스턴스 및 엔진 설정
      DBName: "travelog" # DB 이름
      Engine: mysql
      EngineVersion: "8.0.43"
      Port: 3306
      DBInstanceClass: db.t3.micro
      MasterUsername: !Ref DbMasterUsername
      MasterUserPassword: !Ref DbMasterPassword

      # 네트워크 및 고가용성 설정
      DBSubnetGroupName: !Ref RDSDBSubnetGroup
      VPCSecurityGroups:
        - !GetAtt RDSDBSecurityGroup.GroupId
      MultiAZ: true # 고가용성: YES

      # 스토리지 설정
      AllocatedStorage: "20"
      StorageType: gp3

      # 백업 설정
      BackupRetentionPeriod: "7" # 자동 백업: 7일

      # 기타 설정
      PubliclyAccessible: false # 프라이빗 서브넷에 배포되므로 외부 접근 불가
      # Tag for easy identification
      Tags:
        - Key: Project
          Value: "travelogs3-project2"

Outputs:
  DBEndpointAddress:
    Description: RDS DB Instance Endpoint Address
    Value: !GetAtt RDSDBInstance.Endpoint.Address
    Export:
      Name: "travelog-DBEndpoint"

  DBSecurityGroupId:
    Description: RDS Security Group ID
    Value: !Ref RDSDBSecurityGroup
    Export:
      Name: "travelog-DBSecurityGroupId"