AWSTemplateFormatVersion: '2010-09-09'
Description: Create Internet Gateway

Parameters:
  VpcId:
    Type: String

Resources:
  TravelogIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: travelog-igw

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref TravelogIGW
      VpcId: !Ref VpcId

Outputs:
  InternetGatewayId:
    Value: !Ref TravelogIGW